json.id recipe.id
json.title recipe.title
json.prep_time recipe.prep_time
json.servings recipe.servings
json.description recipe.description
json.ingredients recipe.ingredients
json.directions recipe.directions
json.chef recipe.chef
json.image_url recipe.image_url
json.created_at recipe.created_at
json.updated_at recipe.updated_at